baseurl = "https://timmastny.com/"
theme = "hugo-xmin"
languageCode = "en-US"
title = "Tim Mastny"
#disqusshortname = "https-timmastny-netlify-com"
googleAnalytics = "UA-110017486-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "\\.dta$", "blogdown$", "external_data$", "\\.csv$", "external/*"]

[permalinks]
blog = "blog/:slug/"
projects = "/:sections/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    preserveTaxonomyNames = true
    lang = "en"
    paginate = 10
    footer = "Tim Mastny | [Github](https://github.com/tmastny) | [Twitter](https://twitter.com/timmastny) | [LinkedIn](https://www.linkedin.com/in/timothy-mastny-7b438112a/) | [Email](mailto:tim@timmastny.com)"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
