---
title: Use git to Blog(down) About Your Projects
author: ~
date: '2018-01-17'
slug: git-blogdown-projects-workflow
categories: []
tags: []
description: How to use Git to improve blogdown and project workflow 
draft: true
output:
  blogdown::html_page:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, 
                      results='show', cache=FALSE, autodep=FALSE)
knitr::read_chunk("periodization-meta-analysis/tidier.R")
```

## Introduction

Inspired, but dissatified, by [this discussion](https://community.rstudio.com/t/whats-your-blogdown-workflow-to-include-work-from-other-projects/1445) on the RStudio's forum, I'd like to share my workflow to blog about my projects using Hugo/blogdown/Netlify.

Here's the scenario: I'm working on my project, using a git repo to track changes. I'm excited about the project or a certain result, and I'd like to tell everyone about it by making a blog post with blogdown.

But how do I utilize all the work I've already done in the project? I've already curated the data, built the plots, and saved my complicated analysis as a [`.RDS` file](https://www.fromthebottomoftheheap.net/2012/04/01/saving-and-loading-r-objects/). I'd like to reuse that work, and as a one forum user put it "copying rmarkdown files is a nonstarter."

My proposal is to use git, in particular [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules), along with knitr [code externalization](https://yihui.name/knitr/demo/externalization/) to faciliate the reuse of code when writing blog posts. 

I'll work through this by example. Please see the [Github repo](https://github.com/tmastny/git-blogdown-workflow) I created for this blog post. The scripts and data within the repo will be the external project we'd like to blog about. 

## git Setup

For our purposes, we'll assume your git repo exists locally and on Github. I strongly recommend working through Jenny Bryan's excellence bookdown on [git for R users](http://happygitwithr.com/index.html)




