---
title: 'R Snytax Highlighting in blogdown'
author: ~
date: '2020-06-20'
slug: r-syntax-highlight-blogdown-hugo
categories: []
tags: []
description:
draft: true
output:
  blogdown::html_page:
    toc: true
---

```{r setup, include=FALSE}
library(magrittr)
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE,
                      results='show', cache=FALSE, autodep=FALSE)

code <- '#123456789#123456789#123456789#123456789#123456789#123456789#123456789#123456789
library(tidyverse)

urchins <- read_csv("https://tidymodels.org/start/models/urchins.csv") %>%
  setNames(c("food_regime", "initial_volume", "width")) %>%
  mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))

urchins %>%
  group_by(food_regime) %>%
  summarise(
    across(everything(), mean), n = n()
  )'
```

Distinct between theme and parsing.



Hugo shortcodes

```{r}
blogdown::shortcode_html("highlight", "r", .content = code)
```

highlight.js

```{r eval=FALSE}
#123456789#123456789#123456789#123456789#123456789#123456789#123456789#123456789
library(tidyverse)

urchins <- read_csv("https://tidymodels.org/start/models/urchins.csv") %>%
  setNames(c("food_regime", "initial_volume", "width")) %>%
  mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))

urchins %>%
  group_by(food_regime) %>%
  summarise(
    across(everything(), mean), n = n()
  )
```

There is also the highlight [R package](https://github.com/romainfrancois/highlight),
which does semantic highlighting, where words have
unique coloring depending on the context.

```{r echo=FALSE, results='asis'}
library(highlight)
highlight(code, detective = sherlock()) %>% cat()
```

pandoc themes. They are conclusively covered here,
so I won't provide a full array: https://www.garrickadenbuie.com/blog/pandoc-syntax-highlighting-examples/

https://github.com/rstudio/blogdown/issues/360
